"""
A simple safety mechanism for checking inputs and outputs.
This provides a basic structure for implementing safety guards.
"""

from typing import List

class GuardManager:
    """
    Manages and applies safety checks (guards) during an agent run.
    """

    def __init__(self, safe_mode: bool = True):
        """
        Initializes the GuardManager.

        Args:
            safe_mode: If True, more restrictive checks are applied.
        """
        self.safe_mode = safe_mode

        # Example deny list. In a real application, this would be more extensive.
        self.deny_list: List[str] = ["secret_key", "password", "api_key"]

    def check_prompt(self, prompt: str) -> bool:
        """
        Checks the prompt before sending it to a model.
        For now, this is a simple placeholder.

        Args:
            prompt: The prompt string to be checked.

        Returns:
            True if the prompt is considered safe, False otherwise.
        """
        # In safe mode, we might prevent certain words from being sent.
        if self.safe_mode:
            if any(denied_word in prompt.lower() for denied_word in self.deny_list):
                print(f"Guard Alert: Prompt contains a denied word.")
                return False
        return True

    def check_model_output(self, text_output: str) -> bool:
        """
        Checks the output received from a model.

        Args:
            text_output: The text generated by the model.

        Returns:
            True if the output is considered safe, False otherwise.
        """
        # This could be used to check for harmful content, PII, etc.
        # For now, it's a simple placeholder.
        if self.safe_mode:
             if len(text_output) > 4096: # Arbitrary length limit
                 print("Guard Alert: Model output exceeds length limit.")
                 return False
        return True

# A global instance that can be used by the orchestrator.
guard_manager = GuardManager(safe_mode=True)
